package model;
// Generated Nov 26, 2019, 5:21:03 PM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;




/**
 * Dispotravail generated by hbm2java
 */
@Entity
@Table(name="dispotravail")
public class Dispotravail implements java.io.Serializable {

	private static final long serialVersionUID = 1L; 

	@Id
	@GeneratedValue
	private long id;
	@ManyToOne
	private Users users;
	@Column(name="heureDebut")
	private LocalTime heureDebut;
	private LocalTime heureFin;
	private LocalDate date;

	public Dispotravail() {
	}

	public Dispotravail(long id, Users users) {
		this.id = id;
		this.users = users;
	}

	public Dispotravail(long id, Users users, LocalTime heureDebut, LocalTime heureFin, LocalDate date) {
		this.id = id;
		this.users = users;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.date = date;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public LocalTime getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(LocalTime heureDebut) {
		this.heureDebut = heureDebut;
	}

	public LocalTime getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(LocalTime heureFin) {
		this.heureFin = heureFin;
	}

	public LocalDate getDate() {
		return this.date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return "Dispotravail [id=" + id + ", users=" + users + ", heureDebut=" + heureDebut + ", heureFin=" + heureFin
				+ ", date=" + date + "]";
	}

}
