package model;
// Generated Nov 26, 2019, 5:21:03 PM by Hibernate Tools 5.4.3.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 * Medecinremp generated by hbm2java
 */
@Entity
public class Medecinremp implements java.io.Serializable {

	private static final long serialVersionUID = 1L; 

	@Id
	@GeneratedValue
	private long id;
	@ManyToOne
	private Specialite specialite;
	@OneToOne
	private Users users;
	private Long kmmax;
	private double longitude;
	private double lattitude;
	private String description;
	private String cv;
	private String cartePro;
	@OneToMany(mappedBy = "medecinremp")
	private Set<Mission> missions = new HashSet<Mission>(0);

	public Medecinremp() {
	}

	public Medecinremp(long id, Users users, double longitude, double lattitude) {
		this.id = id;
		this.users = users;
		this.longitude = longitude;
		this.lattitude = lattitude;
	}

	public Medecinremp(long id, Specialite specialite, Users users, Long kmmax, double longitude, double lattitude,
			String description, String cv, String cartePro, Set<Mission> missions) {
		this.id = id;
		this.specialite = specialite;
		this.users = users;
		this.kmmax = kmmax;
		this.longitude = longitude;
		this.lattitude = lattitude;
		this.description = description;
		this.cv = cv;
		this.cartePro = cartePro;
		this.missions = missions;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Specialite getSpecialite() {
		return this.specialite;
	}

	public void setSpecialite(Specialite specialite) {
		this.specialite = specialite;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Long getkmmax() {
		return this.kmmax;
	}

	public void setkmmax(Long kmmax) {
		this.kmmax = kmmax;
	}

	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public double getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(double lattitude) {
		this.lattitude = lattitude;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Serializable getCv() {
		return this.cv;
	}

	public void setCv(String cv) {
		this.cv = cv;
	}

	public Serializable getCartePro() {
		return this.cartePro;
	}

	public void setCartePro(String cartePro) {
		this.cartePro = cartePro;
	}

	public Set<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(Set<Mission> missions) {
		this.missions = missions;
	}

	@Override
	public String toString() {
		return "Medecinremp [id=" + id + ", specialite=" + specialite + ", users=" + users + ", kmmax=" + kmmax
				+ ", longitude=" + longitude + ", lattitude=" + lattitude + ", description=" + description + ", cv="
				+ cv + ", cartePro=" + cartePro + ", missions=" + missions + "]";
	}

}
