package model;
// Generated Nov 26, 2019, 5:21:03 PM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Specialite generated by hbm2java
 */
@Entity
public class Specialite implements java.io.Serializable {

	private static final long serialVersionUID = 1L; 

	@Id
	@GeneratedValue
	private long id;
	private Character nom;
	@OneToMany(mappedBy = "specialite")
	private Set<Medecinremp> medecinremps = new HashSet<Medecinremp>(0);

	public Specialite() {
	}

	public Specialite(long id) {
		this.id = id;
	}

	public Specialite(long id, Character nom, Set<Medecinremp> medecinremps) {
		this.id = id;
		this.nom = nom;
		this.medecinremps = medecinremps;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Character getNom() {
		return this.nom;
	}

	public void setNom(Character nom) {
		this.nom = nom;
	}

	public Set<Medecinremp> getMedecinremps() {
		return this.medecinremps;
	}

	public void setMedecinremps(Set<Medecinremp> medecinremps) {
		this.medecinremps = medecinremps;
	}

}
