package model;
// Generated Nov 26, 2019, 5:21:03 PM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;


/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 1L; 

	@Id
	@GeneratedValue
	private long id;
	private String mail;
	private long telephone;
	private String mdp;
	private boolean isemployeur;
	@OneToOne(mappedBy = "users")
	private Medecinremp medecinremp;
	@OneToMany(mappedBy = "users")
	private Set<Dispotravail> dispotravails = new HashSet<Dispotravail>(0);
	@OneToOne(mappedBy = "users")
	private Employeur employeur;

	public Users() {
	}

	public Users(long id, String mail, long telephone, String mdp, boolean isemployeur) {
		this.id = id;
		this.mail = mail;
		this.telephone = telephone;
		this.mdp = org.apache.commons.codec.digest.DigestUtils.sha256Hex(mdp);
		this.isemployeur = isemployeur;
	}

	public Users(long id, String mail, long telephone, String mdp, boolean isemployeur,Medecinremp medecinremp, Set<Dispotravail> dispotravails, Employeur employeur) {
		this.id = id;
		this.mail = mail;
		this.telephone = telephone;
		this.mdp = org.apache.commons.codec.digest.DigestUtils.sha256Hex(mdp);
		this.isemployeur = isemployeur;
		this.medecinremp = medecinremp;
		this.dispotravails = dispotravails;
		this.employeur = employeur;
	}
	
	public boolean getIsemployeur() {
		return this.isemployeur;
	}
	public void setIsemployeur(boolean isemployeur) {
		this.isemployeur = isemployeur;
	}
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = org.apache.commons.codec.digest.DigestUtils.sha256Hex(mdp);
	}

	public Medecinremp getMedecinremp() {
		return this.medecinremp;
	}

	public void setMedecinremp(Medecinremp medecinremp) {
		this.medecinremp = medecinremp;
	}

	public Set<Dispotravail> getDispotravails() {
		return this.dispotravails;
	}

	public void setDispotravails(Set<Dispotravail> dispotravails) {
		this.dispotravails = dispotravails;
	}

	public Employeur getEmployeur() {
		return this.employeur;
	}

	public void setEmployeur(Employeur employeur) {
		this.employeur = employeur;
	}

	@Override
	public String toString() {
		return "Users [id=" + id + ", mail=" + mail + ", telephone=" + telephone + ", mdp=" + mdp + ", employeurs=" + employeur + "]";
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Users other = (Users) obj;
		if (id != other.id)
			return false;
		if (mail == null) {
			if (other.mail != null)
				return false;
		} else if (!mail.equals(other.mail))
			return false;
		if (mdp == null) {
			if (other.mdp != null)
				return false;
		} else if (!mdp.equals(other.mdp))
			return false;
		if (telephone != other.telephone)
			return false;
		return true;
	}

}
